version: '3'
services:
  url-shortener:
    container_name: url-shortener
    pull_policy: build
    build: .
    ports:
      - 4173:4173
    labels:
      - 'traefik.http.routers.url-shortener.rule=Host(`url.cheekysim.com`)'
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_default
