version: '3'
services:
  url-shortener:
    container_name: url-shortener
    pull_policy: build
    build: .
    environment:
      - MONGO_IP=${MONGO_IP}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - API_TOKEN=${API_TOKEN}
      - ORIGIN=${ORIGIN}
    ports:
      - 4173:4173
    restart: unless-stopped
