version: '3'
services:
  url-shortener-server:
    container_name: url-shortener-server
    pull_policy: build
    build: .
    environment:
      - MONGO_IP=${MONGO_IP}
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - API_KEY=${API_KEY}
    ports:
      - 4005:4005
    restart: unless-stopped
