version: '3'
services:
  url-shortener-client:
    container_name: url-shortener-client
    pull_policy: build
    build: .
    environment:
      - API_KEY=${API_KEY}
      - API_ORIGIN=${API_ORIGIN}
      - SERVER_PORT=4006
    ports:
      - 4006:4006
    restart: unless-stopped
