export async function load({ params }): Promise<{ url: string }> {
	const response = await fetch('http://localhost:3005/api/v1/data');
	const data: Data[] = await response.json();
	console.log(data);
	data.forEach((url) => {
		if (url.short === params.short) {
			return { url: url.long };
		}
	});
	return { url: 'https://www.google.com' };
}

// Generated by https://quicktype.io

export interface Data {
	_id: string;
	long: string;
	short: string;
}
